In [1]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 4.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

A= np.array([[1,2,3],[4,5,6],[7,8,9]])
print('---matriz A---\n',A,'\n')
B= np.array([[10,20,30],[40,50,60],[70,80,90]])
print('---matriz B---\n',B)

---matriz A---
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

---matriz B---
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
print(A*B)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [6]:
print(A/B)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [7]:
print(A.max())
print(A.min())

9
1


In [9]:
print(A.max(axis=0))
print(A.max(axis=1))

[7 8 9]
[3 6 9]


In [10]:
n=3
m=4
C =np.random.rand(n,m)
print(C)

[[0.00778626 0.67537081 0.92212462 0.98999201]
 [0.87986836 0.66962001 0.7691849  0.63184164]
 [0.80949166 0.12841967 0.74925454 0.47396023]]


In [11]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
D= np.array([[1,2,-1],[10,-5,0],[6,3,1]])
print(D)

[[ 1  2 -1]
 [10 -5  0]
 [ 6  3  1]]


In [13]:
E = np.sort(D,axis=0)
print(E)

[[ 1 -5 -1]
 [ 6  2  0]
 [10  3  1]]


In [14]:
E = np.sort(D,axis=1)
print(E)

[[-1  1  2]
 [-5  0 10]
 [ 1  3  6]]


In [16]:
F= np.array([[4,8],[6,1]])
print(F,'\n')
G= np.array([[3,5],[7,2]])
print(G,'\n')
print(np.hstack((F,G)),'\n')
print(np.vstack((F,G)))

[[4 8]
 [6 1]] 

[[3 5]
 [7 2]] 

[[4 8 3 5]
 [6 1 7 2]] 

[[4 8]
 [6 1]
 [3 5]
 [7 2]]


In [19]:
C=np.dot(A,B)

In [20]:
print(C)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [22]:
data = np.array([('joe',2,2.4),('mary',5,3.2),('john',6,1.5)], 
                dtype=[('nome',str,10),('idade', int),('altura',float)])
print(data)

[('joe', 2, 2.4) ('mary', 5, 3.2) ('john', 6, 1.5)]


In [23]:
print('Nomes: ',data['nome'])
print('idades: ',data['idade'])
print('alturas: ',data['altura'])

Nomes:  ['joe' 'mary' 'john']
idades:  [2 5 6]
alturas:  [2.4 3.2 1.5]


In [24]:
data[0]

('joe', 2, 2.4)

In [27]:
!pip install pandas


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import pandas as pd

In [29]:
X={'X1':[1,2,3,4,5,6,7,8],'X2': ['a','b','c', 'd','e','f','g','h'], 'X3':[.2,.4,.5,.6,.7,.8,.9,1.]}
df =pd.DataFrame(data=X)
df.head()

X1 X2   X3
0   1  a  0.2
1   2  b  0.4
2   3  c  0.5
3   4  d  0.6
4   5  e  0.7

In [30]:
print(df.iloc[2,1])

c


In [31]:
print(df.iloc[3,:])

X1      4
X2      d
X3    0.6
Name: 3, dtype: object


In [32]:
I = np.array(df)
print(I)

[[1 'a' 0.2]
 [2 'b' 0.4]
 [3 'c' 0.5]
 [4 'd' 0.6]
 [5 'e' 0.7]
 [6 'f' 0.8]
 [7 'g' 0.9]
 [8 'h' 1.0]]


In [33]:
data = pd.read_csv('iris.csv', header =(0))
print("Numero de linhas e colunas = ", data.shape)
data.head(10)

Numero de linhas e colunas =  (150, 5)


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa