In [1]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 4.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

A= np.array([[1,2,3],[4,5,6],[7,8,9]])
print('---matriz A---\n',A,'\n')
B= np.array([[10,20,30],[40,50,60],[70,80,90]])
print('---matriz B---\n',B)

---matriz A---
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

---matriz B---
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
print(A*B)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [6]:
print(A/B)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [7]:
print(A.max())
print(A.min())

9
1


In [9]:
print(A.max(axis=0))
print(A.max(axis=1))

[7 8 9]
[3 6 9]


In [10]:
n=3
m=4
C =np.random.rand(n,m)
print(C)

[[0.00778626 0.67537081 0.92212462 0.98999201]
 [0.87986836 0.66962001 0.7691849  0.63184164]
 [0.80949166 0.12841967 0.74925454 0.47396023]]


In [11]:
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
D= np.array([[1,2,-1],[10,-5,0],[6,3,1]])
print(D)

[[ 1  2 -1]
 [10 -5  0]
 [ 6  3  1]]


In [13]:
E = np.sort(D,axis=0)
print(E)

[[ 1 -5 -1]
 [ 6  2  0]
 [10  3  1]]


In [14]:
E = np.sort(D,axis=1)
print(E)

[[-1  1  2]
 [-5  0 10]
 [ 1  3  6]]


In [16]:
F= np.array([[4,8],[6,1]])
print(F,'\n')
G= np.array([[3,5],[7,2]])
print(G,'\n')
print(np.hstack((F,G)),'\n')
print(np.vstack((F,G)))

[[4 8]
 [6 1]] 

[[3 5]
 [7 2]] 

[[4 8 3 5]
 [6 1 7 2]] 

[[4 8]
 [6 1]
 [3 5]
 [7 2]]
